### ISSUE TITLE
It's doesn't work

### ISSUE THREAD

**Issue by dimka11** [vue-leaflet/vue-leaflet#299] opened 2023-04-22 10:22 UTC
I have tried simple example from readme in my Vue3 project but get:

```
[Vue warn]: Unhandled error during execution of mounted hook 
  at <LMap ref="map" zoom=2 onUpdate:zoom=fn  ... > 
  at <Leaflet> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:40
Show 1 more frame
vue-leaflet.es.js:46 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Default')
    at Ye (vue-leaflet.es.js:46:12)
    at async vue-leaflet.es.js:1205:7
```

**Comment by mikeu** [comment] 2023-04-22 17:22
Hi @dimka11 , this looks to be a duplicate of #278 , do any of the solutions in that thread work for you?

**Closed** 2023-06-16 06:07 UTC
Labels: duplicate
