### ISSUE TITLE
Map not working in total

### ISSUE THREAD

**Issue by AndreasBuc** [vue-leaflet/vue-leaflet#327] opened 2023-07-12 19:44 UTC
Hello, I am encountering and issue. 

I made a clean vue app with only:

```
npm i -D @vue-leaflet/vue-leaflet leaflet
```
so I have these packages

```
{
  "name": "test",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "run-p type-check build-only",
    "preview": "vite preview",
    "build-only": "vite build",
    "type-check": "vue-tsc --noEmit -p tsconfig.app.json --composite false"
  },
  "dependencies": {
    "vue": "^3.3.4"
  },
  "devDependencies": {
    "@tsconfig/node18": "^2.0.1",
    "@types/node": "^18.16.17",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue-leaflet/vue-leaflet": "^0.10.1",
    "@vue/tsconfig": "^0.4.0",
    "i": "^0.3.7",
    "leaflet": "^1.9.4",
    "npm": "^9.8.0",
    "npm-run-all": "^4.1.5",
    "typescript": "~5.0.4",
    "vite": "^4.3.9",
    "vue-tsc": "^1.6.5"
  }
}
```

and in the app.vue I use code from an example:

```
<template>
  <div style="height: 600px; width: 800px">
    <l-map
      ref="map"
      v-model:zoom="zoom"
      :center="[47.41322, -1.219482]"
    >
      <l-tile-layer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        layer-type="base"
        name="OpenStreetMap"
      ></l-tile-layer>
    </l-map>
  </div>
</template>
<script setup lang="ts">
  import "leaflet/dist/leaflet.css";
  import { LMap, LTileLayer } from "@vue-leaflet/vue-leaflet";
  import { ref } from "vue";

  const zoom = ref(2);
</script>
```

with results in this error code:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Default')
    at qe (vue-leaflet.es.js:47:12)
    at async vue-leaflet.es.js:1310:7
```
clicking on "(vue-leaflet.es.js:47:12)"
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Default') ->
delete e.Default.prototype._getIconUrl, e.Default.mergeOptions({
    iconRetinaUrl: o[0].default,
    iconUrl: o[1].default,
    shadowUrl: o[2].default
  });
```
Am I doing something wrong maybe??

Thanks for your time :)

Best regards
Andreas
![Screenshot 2023-07-12 214249](https://github.com/vue-leaflet/vue-leaflet/assets/63713732/a9e0d680-d269-4b33-ba38-a0ab41123974)
![Screenshot 2023-07-12 214309](https://github.com/vue-leaflet/vue-leaflet/assets/63713732/aa0d6316-e156-4198-adff-019cef6229e7)

**Comment by joshstrange** [comment] 2023-07-16 16:37
Same issue here, I tried multiple versions of `leaflet` and `@vue-leaflet/vue-leaflet` but I keep getting that same error. 

I dug into the code some more and it looks like adding `:useGlobalLeaflet="false"` to the `l-map` component fixes this. By default this library seems to be looking in the global namespace for leaflet instead of using the peerDependency.

**Comment by mikeu** [comment] 2023-07-16 18:27
Thank you for your detailed issue report, @AndreasBuc ! From the description, I believe this is a duplicate of #278 in which there is some discussion around how vite's dev mode causes this problem, though its preview mode does not seem to.

@joshstrange thanks for looking into this as well! You are correct that by default vue-leaflet uses Leaflet from where it installs itself in the global namespace, unless you tell it not to by setting `:useGlobalLeaflet="false"` as you say. In either case though, it uses whichever version you have installed in your project to satisfy the peer dependency.

**Closed as not planned by mikeu** 2023-07-16 18:27 UTC
Labels: duplicate

**Comment by AndreasBuc** [comment] 2023-07-16 18:41
thanks for your reply :)
