### ISSUE TITLE
How to use it with Nuxt 3 TypeScript 

### ISSUE THREAD

**Issue by geofany** [vue-leaflet/vue-leaflet#320] opened 2023-06-18 09:37 UTC
hello i'm using Nuxt 3 TypeScript 
`"nuxt": "^3.5.2"`
`"@vue-leaflet/vue-leaflet": "^0.10.1"`
`"leaflet": "^1.9.4"`

and the component
```
<template>
  <div style="height:600px; width:800px">
    <l-map ref="map" :zoom="zoom" :center="[47.41322, -1.219482]">
      <l-tile-layer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" layer-type="base"
        name="OpenStreetMap"></l-tile-layer>
    </l-map>
  </div>
</template>

<script setup lang="ts">
import "leaflet/dist/leaflet.css";
import { LMap, LTileLayer } from "@vue-leaflet/vue-leaflet";

const zoom = ref<number>(2)
</script>

<style scoped></style>
```

but it's show error when i run it
<img width="640" alt="Screenshot 2023-06-18 at 16 36 11" src="https://github.com/vue-leaflet/vue-leaflet/assets/37582643/ad369ba2-e268-4219-9688-09e7c5ed5860">

**Comment by xlrx** [comment] 2023-06-19 23:25
Exact same error here with vite

Edit: 
This solution works for me: https://github.com/vue-leaflet/vue-leaflet/issues/312#issuecomment-1567407915

**Comment by geofany** [comment] 2023-06-20 06:40
yes, i use it like this and works fine
```
<l-map ref="map" :zoom="zoom" :min-zoom="minZoom" :max-zoom="maxZoom" :center="center" :useGlobalLeaflet="false">
</l-map>
```

**Comment by mikeu** [comment] 2023-06-25 21:29
Yep, duplicate of #278 .

**Closed as not planned by mikeu** 2023-06-25 21:29 UTC
Labels: duplicate
