### ISSUE TITLE
vue-leaflet Routing

### ISSUE THREAD

**Issue by UnLegitCombos** [vue-leaflet/vue-leaflet#314] opened 2023-05-29 21:10 UTC
Basically what I'm coding is a E-Bike Sharing website, a JSON with a bunch of charging station all throughout NYC was given to me, my goal is to have a map where I can input 2 addresses or coordinates (start and end position) , the website will have to search for the closest station to both positions and guide me.

I had searched a bit before and I'm pretty sure that you can't use only one routing.control object for this and need 3, because from the start position to the first station it's on foot, from the first station to the second one is by bike and back on foot for the last bit, as you can't separate the route in 3 parts (at least I think so?). But when I started coding I found this package and it was so easy to use, unfortunately now that I've gotten to the routing bit I don't seem to find anything that works, the package doesn't seem to have it included and in the discord nobody responded. I noticed [another package](https://www.npmjs.com/package/leaflet-routing-machine) that most people, including my classmates (who aren't using Vue btw) are using, and even though I knew it was barely maintained I gave it a try, unfortunately I don't think the 2 package work together or perhaps I'm just dumb and couldn't make it work.

I saw one other person had the same problem in a GitHub issue on the first package's page but nobody answered, hoping to get a bit more help than I have, because I have been stuck to no avail for the past few days and the project is due soon.

leaflet@1.9.3
vue@3.2.47
leaflet-routing-machine@3.2.12
vue-leaflet@0.9.0

**Comment by mikeu** [comment] 2023-06-16 05:58
Hi @UnLegitCombos , at the moment we do not have any documentation around adding new plugins unfortunately. However, Leaflet's plugins all work very similarly to its core components, so hopefully following the patterns used for each of e.g. `components/LPolygon.vue` and `functions/polygon.ts` or `components/LIcon.vue` and `functions/icon.ts`, etc., will put you on the right track for your homework!

**Comment by mikeu** [comment] 2023-06-16 05:58
Duplicate of #293

**Closed by mikeu** 2023-06-16 05:58 UTC
Labels: duplicate, plugin
